### ISSUE TITLE
When calculating time, do not include closed tasks

### ISSUE THREAD

**Issue by sashika** [hungrymedia/checkvist-estimator-chrome-extension#8]

**Comment by hungrymedia** [comment]
I need to put some thought into implementing this request. I think users will need to option to remove closed tasks from totals or not. Some people may be using this to estimate a full project's time, rather than remaining time. If you have implementation ideas, I'd love to hear them.

**Comment by hungrymedia** [comment]
I went ahead and added a new option to the extension that allows the user to choose whether or not to include closed items in totals. v1.3.3 should be in the Chrome Web Store momentarily. Thanks for the suggestion.

**Comment by sashika** [comment]
Warren, you are awesome, do you know that? :)

**Comment by hungrymedia** [comment]
Ha ha. Thanks
