### ISSUE TITLE
Top list item time is not re-calculated to zero after I've closed the last tagged sub-item

### ISSUE THREAD

**Issue by sashika** [hungrymedia/checkvist-estimator-chrome-extension#9]
I'd expect a top tag to disappear or - better - show me the '0' value after I've closed the last tagged sub-item, but it still shows the previous time (10h).

**Comment by hungrymedia** [comment]
I did some testing this morning and am seeing that the hours for parent tasks are already removed if all child tasks are closed and options are set to NOT calculate closed tasks. See video at http://www.youtube.com/watch?v=rzblQxkEBwI for my tests. 

Please confirm this is an issue for you. If so, if you can provide me with steps, that'd be very helpful.

Thanks.

**Comment by sashika** [comment]
Hello! Sorry, took me a bit longer than expected.
Unfortunately, the bug's still here for me (Chrome 19, MacOSx), pls, see the demonstration http://dl.dropbox.com/u/238239/timeCalcBug.mov

**Comment by hungrymedia** [comment]
Well that's no good, is it? I'll get this sorted out ASAP. Busy week for me, so it might not be until the coming weekend.

**Comment by sashika** [comment]
Sure! thanks, a lot!
this plugin will make a time tracking addict of me ;)

**Comment by hungrymedia** [comment]
Me too. No more spreadsheets! ;)

On Mon, Jun 25, 2012 at 2:15 PM, sashika <
reply@reply.github.com

> wrote:
> 
> Sure! thanks, a lot!
> this plugin will make a time tracking addict of me ;)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/hungrymedia/checkvist-estimator-chrome-extension/issues/9#issuecomment-6555299

## 

Warren Harrison
interactive developer
warren@hungry-media.com

**Comment by hungrymedia** [comment]
This is fixed now. The issue was that the I was sending an empty string as the tag string via the API for tasks that have no tags after the time is removed. That didn't seem to get actually set the tags to empty. I worked around by simply adding a single comma in those cases.

**Comment by hungrymedia** [comment]
Closed by ca9c92f5a00df41f4911bcdbf8cf6409f92985e4

**Comment by sashika** [comment]
Thanks a lot -- works like a charm now!
